# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy email extractor timer to Azure Functions - ah-pipelines

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './email_extractor' # deploy the function subfolder
  PYTHON_VERSION: '3.11'
  AZURE_FUNCTIONAPP_NAME: 'bot-agentic'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: |
          # Create a lean package: exclude venv, local dev files, and large docs
          zip -r "$GITHUB_WORKSPACE/release.zip" . \
            -x "venv/**" \
               "*.pdf" \
               "**/*.pdf" \
               "local.settings.json" \
               "Dockerfile" \
               "README.md"

      - name: Check packaged artifact exists
        shell: bash
        run: |
          ls -lah "$GITHUB_WORKSPACE" || true
          test -f "$GITHUB_WORKSPACE/release.zip" && echo "release.zip found" || (echo "release.zip missing" && exit 1)

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: ${{ github.workspace }}/release.zip
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip -d package
          rm release.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EC3B302D2CF14B899DAD01782122E729 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_45942ADCA3014052B164ECB7DB967BE0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6F686442926940B2AE483A263037D194 }}

      - name: Verify Function App exists and print properties
        uses: azure/CLI@v2
        with:
          inlineScript: |
            RG=$(az functionapp list --query "[?name=='${{ env.AZURE_FUNCTIONAPP_NAME }}'].resourceGroup | [0]" -o tsv)
            if [ -z "$RG" ]; then
              echo "Function App ${{ env.AZURE_FUNCTIONAPP_NAME }} not found in current subscription.";
              exit 1
            fi
            echo "Resource Group: $RG"
            az functionapp show --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group "$RG" \
              --query "{name:name, location:location, state:state, kind:kind, reserved:reserved, linuxFxVersion:siteConfig.linuxFxVersion, serverFarmId:serverFarmId}" -o yaml

      - name: Ensure storage account name for deployment (AzureWebJobsStorage__accountName)
        uses: azure/CLI@v2
        with:
          inlineScript: |
            set -e
            APP="${{ env.AZURE_FUNCTIONAPP_NAME }}"
            RG=$(az functionapp list --query "[?name=='$APP'].resourceGroup | [0]" -o tsv)
            echo "Checking storage account settings for $APP in $RG"
            ACCOUNT_NAME=$(az functionapp config appsettings list --name "$APP" --resource-group "$RG" --query "[?name=='AzureWebJobsStorage__accountName'].value" -o tsv)
            if [ -z "$ACCOUNT_NAME" ]; then
              CONN=$(az functionapp config appsettings list --name "$APP" --resource-group "$RG" --query "[?name=='AzureWebJobsStorage'].value" -o tsv)
              if [ -n "$CONN" ]; then
                ACCOUNT_NAME=$(echo "$CONN" | sed -n "s/.*AccountName=\([^;]*\).*/\1/p")
              fi
            fi
            if [ -z "$ACCOUNT_NAME" ]; then
              SECRET_CONN=$(az functionapp config appsettings list --name "$APP" --resource-group "$RG" --query "[?name=='AzureWebJobsSecretStorage'].value" -o tsv)
              if [ -n "$SECRET_CONN" ]; then
                ACCOUNT_NAME=$(echo "$SECRET_CONN" | sed -n "s/.*AccountName=\([^;]*\).*/\1/p")
              fi
            fi
            if [ -z "$ACCOUNT_NAME" ]; then
              echo "ERROR: Could not determine storage account name. Set 'AzureWebJobsStorage' or 'AzureWebJobsStorage__accountName' in app settings.";
              exit 1
            fi
            echo "Using storage account: $ACCOUNT_NAME"
            az functionapp config appsettings set \
              --name "$APP" \
              --resource-group "$RG" \
              --settings AzureWebJobsStorage__accountName="$ACCOUNT_NAME"

      - name: Ensure Function App Python runtime (LinuxFxVersion)
        uses: azure/CLI@v2
        with:
          inlineScript: |
            RG=$(az functionapp list --query "[?name=='${{ env.AZURE_FUNCTIONAPP_NAME }}'].resourceGroup | [0]" -o tsv)
            az functionapp config set \
              --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
              --resource-group "$RG" \
              --linux-fx-version "Python|3.11"

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'Production'
          package: package
          scm-do-build-during-deployment: true

      - name: Verify functions are indexed
        uses: azure/CLI@v2
        with:
          inlineScript: |
            RG=$(az functionapp list --query "[?name=='${{ env.AZURE_FUNCTIONAPP_NAME }}'].resourceGroup | [0]" -o tsv)
            echo "Listing functions for app ${{ env.AZURE_FUNCTIONAPP_NAME }} in resource group $RG"
            az functionapp function list --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group "$RG" -o table || true
          