# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Deploy Azure Function App - bot-agentic (ai_bot)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './ai_bot' # deploy the ai_bot subfolder
  AZURE_FUNCTIONAPP_NAME: 'bot-agentic'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EC3B302D2CF14B899DAD01782122E729 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_45942ADCA3014052B164ECB7DB967BE0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6F686442926940B2AE483A263037D194 }}

      # Optional: set app settings from secrets (uncomment if you want CI to manage them)
      # - name: Set Function App settings
      #   uses: azure/CLI@v2
      #   with:
      #     inlineScript: |
      #       set -euo pipefail
      #       APP_NAME='${{ env.AZURE_FUNCTIONAPP_NAME }}'
      #       RG=$(az functionapp list --query "[?name=='${{ env.AZURE_FUNCTIONAPP_NAME }}'].resourceGroup | [0]" -o tsv)
      #       az functionapp config appsettings set \
      #         --name "$APP_NAME" \
      #         --resource-group "$RG" \
      #         --settings \
      #           OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}' \
      #           PINECONE_API_KEY='${{ secrets.PINECONE_API_KEY }}' \
      #           PINECONE_HOST='${{ secrets.PINECONE_HOST }}' \
      #           META_VERIFY_TOKEN='${{ secrets.META_VERIFY_TOKEN }}' \
      #           META_WABA_TOKEN='${{ secrets.META_WABA_TOKEN }}' \
      #           META_PHONE_NUMBER_ID='${{ secrets.META_PHONE_NUMBER_ID }}' \
      #           LLM_PROVIDER='hf' \
      #           EMBEDDING_PROVIDER='openai' \
      #           ADMIN_API_KEY='${{ secrets.ADMIN_API_KEY }}'

      - name: Deploy to Azure Functions (ai_bot folder)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          